name: git-ondra
summary: git client
description: |
 git client as snap
 To setup aliases for git command, run: $ /snap/git-ondra/current/usr/bin/set-aliases

base: core24

confinement: strict
grade: stable
adopt-info: git

platforms:
  armhf:
  arm64:
  amd64:
  riscv64:

environment:
  PATH: $SNAP/usr/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
  # use COMMON data as home dir instead of per revision home
  HOME: $SNAP_USER_COMMON

layout:
  /usr/lib/git-core:
    bind: $SNAP/usr/lib/git-core
  /usr/share/git-core:
    bind: $SNAP/usr/share/git-core

apps:
  git:
    command: usr/bin/git
    completer: git-completion.bash
    plugs:
      - network-bind
      - home
      - removable-media
      - ssh-keys

  receive-pack:
    command: usr/bin/git-receive-pack
    completer: git-completion.bash
    plugs:
      - network-bind
      - home
      - removable-media
      - ssh-keys

  shell:
    command: usr/bin/git-shell
    completer: git-completion.bash
    plugs:
      - network-bind
      - home
      - removable-media
      - ssh-keys

  upload-archive:
    command: usr/bin/git-upload-archive
    completer: git-completion.bash
    plugs:
      - network-bind
      - home
      - removable-media
      - ssh-keys

  upload-pack:
    command: usr/bin/git-upload-pack
    completer: git-completion.bash
    plugs:
      - network-bind
      - home
      - removable-media
      - ssh-keys

parts:
  git:
    plugin: nil
    stage-packages:
      - git
      - openssh-client
    organize:
      usr/share/bash-completion/completions/git: git-completion.bash
    override-build: |
      craftctl default
      version=$(awk \
                    -F ' = ' \
                    '$1 ~ "our \\$version" {gsub(/"/,"",$2); gsub(/;/,"",$2); print $2}' \
                    ${CRAFT_PART_INSTALL}/usr/share/gitweb/gitweb.cgi)
      craftctl set version="${version}"
    stage:
      - -usr/sbin
      - -usr/share/bash-completion
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/perl*
      - -var

  # helper scripts
  glue:
    source: glue
    plugin: dump
